name: Build LaTeX document
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: notes.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: computability_notes
          path: notes.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: notes.pdf

